# Generated by Django 4.2.30 on 2026-06-05 02:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Configuration par défaut', max_length=100, verbose_name='Nom')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Nombre max de tentatives')),
                ('retry_wait_seconds', models.PositiveIntegerField(default=2, verbose_name='Délai entre tentatives (s)')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Timeout API (s)')),
                ('date_tolerance_days', models.PositiveIntegerField(default=0, verbose_name='Tolérance date matching (jours)')),
                ('active', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Batch',
                'db_table': 'configuration_batch',
            },
        ),
        migrations.CreateModel(
            name='EcartDetecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecart', models.CharField(choices=[('EC-01', 'Transaction MB lettrée absente du CBS'), ('EC-02', 'Transaction CBS sans correspondance MB'), ('EC-03', 'Doublon côté CBS'), ('EC-04', 'Doublon côté MB'), ('EC-05', 'Irrévocable non débité'), ('EC-06', 'Irrévocable non crédité')], max_length=10, verbose_name="Type d'écart")),
                ('criticite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('STANDARD', 'Standard')], max_length=10, verbose_name='Criticité')),
                ('type_flux', models.CharField(choices=[('CBS_SIMPLE', 'Transfert simple CBS'), ('PI_EMISSION', 'Paiement Instantané Émission'), ('PI_RECEPTION', 'Paiement Instantané Réception')], max_length=15, verbose_name='Type de flux concerné')),
                ('reference', models.CharField(max_length=255, verbose_name='Référence transaction (end_to_end_id ou message_id)')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Montant concerné')),
                ('compte', models.CharField(blank=True, max_length=100, verbose_name='Compte concerné')),
                ('description', models.TextField(verbose_name="Description de l'écart")),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FAUX_POSITIF', 'Faux positif')], default='NOUVEAU', max_length=15, verbose_name='Statut de traitement')),
                ('date_detection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
            ],
            options={
                'verbose_name': 'Écart Détecté',
                'verbose_name_plural': 'Écarts Détectés',
                'db_table': 'ecart_detecte',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('RESPONSABLE_MB', 'Responsable Mobile Banking'), ('AGENT_BACKOFFICE', 'Agent Back-Office'), ('ADMINISTRATEUR', 'Administrateur')], max_length=30, unique=True, verbose_name='Nom du profil')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'db_table': 'profil',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateField(verbose_name='Date des transactions traitées')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('TERMINEE_SANS_RAPPORT', 'Terminée sans rapport'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=30, verbose_name='Statut')),
                ('declenchement', models.CharField(choices=[('AUTOMATIQUE', 'Automatique (planifié)'), ('MANUEL', 'Manuel')], default='AUTOMATIQUE', max_length=15, verbose_name='Mode de déclenchement')),
                ('heure_debut', models.DateTimeField(auto_now_add=True, verbose_name='Heure de début')),
                ('heure_fin', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur (si statut ERREUR)")),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.configurationbatch', verbose_name='Configuration utilisée')),
                ('declenchee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_declenchees', to=settings.AUTH_USER_MODEL, verbose_name='Déclenchée par (si manuel)')),
            ],
            options={
                'verbose_name': 'Session de Rapprochement',
                'verbose_name_plural': 'Sessions de Rapprochement',
                'db_table': 'reconciliation_session',
                'ordering': ['-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='RapportReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/pdf/', verbose_name='Fichier PDF')),
                ('fichier_excel', models.FileField(blank=True, null=True, upload_to='rapports/excel/', verbose_name='Fichier Excel')),
                ('nb_transactions_mb', models.PositiveIntegerField(default=0, verbose_name='Nb transactions MB')),
                ('nb_transactions_cbs', models.PositiveIntegerField(default=0, verbose_name='Nb transactions CBS')),
                ('nb_ecarts_total', models.PositiveIntegerField(default=0, verbose_name='Nb écarts total')),
                ('nb_ecarts_critiques', models.PositiveIntegerField(default=0, verbose_name='Nb écarts critiques')),
                ('taux_rapprochement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de rapprochement (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='core.reconciliationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Rapport de Rapprochement',
                'db_table': 'rapport_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataires', models.JSONField(default=list, verbose_name='Liste des destinataires')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('corps', models.TextField(verbose_name='Corps du message')),
                ('priorite', models.CharField(choices=[('HAUTE', 'Haute (écart critique)'), ('STANDARD', 'Standard')], max_length=10, verbose_name='Priorité')),
                ('envoyee', models.BooleanField(default=False, verbose_name='Envoyée')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.ecartdetecte', verbose_name='Écart concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetriqueBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_secondes', models.PositiveIntegerField(default=0, verbose_name='Durée totale (s)')),
                ('nb_transactions_mb_collectees', models.PositiveIntegerField(default=0, verbose_name='Transactions MB collectées')),
                ('nb_transactions_cbs_collectees', models.PositiveIntegerField(default=0, verbose_name='Transactions CBS collectées')),
                ('nb_cycles_pi_collectes', models.PositiveIntegerField(default=0, verbose_name='Cycles PI collectés')),
                ('nb_ecarts_detectes', models.PositiveIntegerField(default=0, verbose_name='Écarts détectés')),
                ('nb_erreurs_api', models.PositiveIntegerField(default=0, verbose_name='Erreurs API rencontrées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrique', to='core.reconciliationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Métrique Batch',
                'db_table': 'metrique_batch',
            },
        ),
        migrations.AddField(
            model_name='ecartdetecte',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecarts', to='core.reconciliationsession', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='CyclePI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, verbose_name='Identifiant message PI')),
                ('end_to_end_id', models.CharField(max_length=255, verbose_name='Référence end-to-end')),
                ('direction', models.CharField(choices=[('EMISSION', 'Émission'), ('RECEPTION', 'Réception')], max_length=10, verbose_name='Direction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant')),
                ('funds_reserved', models.BooleanField(default=False, verbose_name='Fonds réservés')),
                ('funds_debited', models.BooleanField(default=False, verbose_name='Fonds débités')),
                ('funds_credited', models.BooleanField(default=False, verbose_name='Fonds crédités')),
                ('statut', models.CharField(max_length=50, verbose_name='Statut PI')),
                ('date_operation', models.DateField(verbose_name="Date d'opération")),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_pi', to='core.reconciliationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Cycle PI',
                'verbose_name_plural': 'Cycles PI',
                'db_table': 'cycle_pi',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.PositiveSmallIntegerField(default=2, verbose_name='Heure de déclenchement (0-23)')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='Minute de déclenchement (0-59)')),
                ('active', models.BooleanField(default=True, verbose_name='Planification active')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_planification', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration Planification',
                'db_table': 'configuration_planification',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action effectuée')),
                ('entite', models.CharField(max_length=100, verbose_name='Entité concernée (nom de table)')),
                ('entite_id', models.CharField(blank=True, max_length=100, verbose_name="ID de l'entité concernée")),
                ('details', models.JSONField(default=dict, verbose_name="Détails de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('nouveau_statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FAUX_POSITIF', 'Faux positif')], max_length=15, verbose_name='Nouveau statut appliqué')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'annotation")),
                ('ecart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='core.ecartdetecte', verbose_name='Écart annoté')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='Annotée par')),
            ],
            options={
                'verbose_name': "Annotation d'Écart",
                'db_table': 'annotation_ecart',
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.profil', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TransactionMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, verbose_name='Identifiant message (message_id)')),
                ('end_to_end_id', models.CharField(max_length=255, verbose_name='Référence end-to-end')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant')),
                ('compte_debiteur', models.CharField(max_length=100, verbose_name='Compte débiteur')),
                ('compte_crediteur', models.CharField(blank=True, max_length=100, verbose_name='Compte créditeur')),
                ('statut', models.CharField(max_length=50, verbose_name='Statut dans le MB')),
                ('type_flux', models.CharField(choices=[('CBS_SIMPLE', 'Transfert simple CBS'), ('PI_EMISSION', 'Paiement Instantané Émission'), ('PI_RECEPTION', 'Paiement Instantané Réception')], max_length=15, verbose_name='Type de flux')),
                ('date_operation', models.DateField(verbose_name="Date d'opération")),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_mb', to='core.reconciliationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Transaction MB',
                'verbose_name_plural': 'Transactions MB',
                'db_table': 'transaction_mb',
                'indexes': [models.Index(fields=['end_to_end_id'], name='transaction_end_to__74f61a_idx'), models.Index(fields=['session', 'type_flux'], name='transaction_session_701fee_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionCBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=255, verbose_name='Identifiant message CBS')),
                ('end_to_end_id', models.CharField(max_length=255, verbose_name='Référence end-to-end')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant')),
                ('debtor_account', models.CharField(max_length=100, verbose_name='Compte débiteur')),
                ('creditor_account', models.CharField(blank=True, max_length=100, verbose_name='Compte créditeur')),
                ('transaction_status', models.CharField(max_length=50, verbose_name='Statut dans le CBS')),
                ('is_pi_transfer', models.BooleanField(default=False, verbose_name='Est un transfert PI')),
                ('timestamp', models.DateTimeField(verbose_name='Horodatage CBS')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cbs', to='core.reconciliationsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Transaction CBS',
                'verbose_name_plural': 'Transactions CBS',
                'db_table': 'transaction_cbs',
                'indexes': [models.Index(fields=['end_to_end_id'], name='transaction_end_to__cb3200_idx'), models.Index(fields=['session', 'is_pi_transfer'], name='transaction_session_136c62_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ecartdetecte',
            index=models.Index(fields=['session', 'type_ecart'], name='ecart_detec_session_197fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartdetecte',
            index=models.Index(fields=['session', 'criticite'], name='ecart_detec_session_aae76f_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartdetecte',
            index=models.Index(fields=['statut'], name='ecart_detec_statut_70de90_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartdetecte',
            index=models.Index(fields=['reference'], name='ecart_detec_referen_a1a5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclepi',
            index=models.Index(fields=['end_to_end_id'], name='cycle_pi_end_to__fa9dca_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclepi',
            index=models.Index(fields=['session', 'direction'], name='cycle_pi_session_40a01b_idx'),
        ),
    ]
